site_name:        Hop.jl
repo_url:         https://github.com/mistguy/Hop.jl
site_description: julia tight binding library
site_author:      mistguy
edit_uri: edit/master/docs/src/

theme:
    name: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite

docs_dir: 'build'

pages:
  - Examples: examples.md
  - API reference: api.md
